'use client'

import "./globals.css";
import { Theme } from '@radix-ui/themes';


// export const metadata: Metadata = {
//   title: "KIM's protfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Theme>

        <main className="flex flex-col w-full mx-auto max-w-screen-2xl">{children}</main>
      </Theme>

    </html>
  );
}
